/**
 * Access Control and User Management Types
 */

export type UserCreationSource = 'MANUAL' | 'BUSINESS_PARTNER' | 'SUB_USER_INVITE';

export interface EnhancedUser {
  id: string;
  email: string;
  name: string;
  
  // User Type
  userType: 'back_office' | 'business_partner' | 'sub_user';
  
  // Business Partner Link
  businessPartnerId?: string;
  businessPartnerName?: string;
  businessPartnerType?: string;
  
  // Branch Access (for data isolation)
  branchIds: string[]; // Empty array = access to all branches
  
  // Sub-User Management
  isSubUser: boolean;
  parentUserId?: string;
  subUserLimit: number; // Maximum sub-users allowed (default: 2)
  subUserCount: number; // Current sub-user count
  
  // Role & Permissions
  roleId: string;
  roleName: string;
  permissions: UserPermission[];
  customPermissions?: Record<string, string[]>; // Module-specific overrides
  
  // Status
  status: 'active' | 'inactive' | 'suspended' | 'pending_approval';
  approvalStatus: 'pending' | 'approved' | 'rejected';
  approvedBy?: string;
  approvedAt?: string;
  
  // Password & Security
  isFirstLogin: boolean;
  requiresPasswordReset: boolean;
  passwordLastChanged?: string;
  passwordExpiresAt?: string;
  failedLoginAttempts: number;
  lockedUntil?: string;
  
  // Creation Source
  creationSource: UserCreationSource;
  autoCreatedFromPartner: boolean;
  
  // Metadata
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  lastLoginAt?: string;
  deactivatedAt?: string;
}

export interface UserPermission {
  moduleId: string;
  moduleName: string;
  actions: string[]; // ['create', 'read', 'update', 'delete']
}

export interface UserRole {
  id: string;
  name: string;
  description: string;
  userType: 'back_office' | 'business_partner';
  permissions: UserPermission[];
  isSystemRole: boolean; // Cannot be deleted/modified
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface SubUserInvite {
  id: string;
  parentUserId: string;
  email: string;
  name: string;
  branchIds: string[];
  permissions: UserPermission[];
  status: 'pending' | 'accepted' | 'expired' | 'cancelled';
  inviteToken: string;
  expiresAt: string;
  createdAt: string;
}

export interface UserCreationFromPartner {
  businessPartnerId: string;
  businessPartnerName: string;
  email: string; // From partner's primary contact email
  name: string; // From partner's primary contact person
  branchIds: string[]; // All branches of the partner
  autoGenerated: boolean;
  pendingApproval: boolean;
}

export interface DataIsolationRule {
  userId: string;
  branchIds: string[]; // User can only see data from these branches
  canViewAllBranches: boolean; // Super Admin / HO staff
  canViewConsolidated: boolean; // Can see consolidated reports
}

export interface ApprovalWorkflow {
  id: string;
  requestType: 'user_creation' | 'user_modification' | 'role_assignment';
  requesterId: string;
  requesterName: string;
  targetUserId?: string;
  targetUserEmail: string;
  details: Record<string, unknown>;
  status: 'pending' | 'approved' | 'rejected';
  approvedBy?: string;
  approvedAt?: string;
  rejectionReason?: string;
  createdAt: string;
}
